### ISSUE TITLE
Extract images and tables from a PDF.

### ISSUE THREAD

**Issue by Le1234125** [gpt-open/rag-gpt#68]
Does rag gpt support parsing images and tables in PDFs?

**Comment by Le1234125** [comment]
Does rag gpt support parsing images and tables in PDFs?

**Comment by blmdxiao** [comment]
This is possible with strategies such as OCR, which was previously validated by local testing.
However, the corresponding model needs to be deployed, and the requirements for the entire deployment resource will be relatively high, and it has not been published on github for the time being.

**Comment by blmdxiao** [comment]
If you have specific requirements for private deployment and would like to discuss further, we can communicate regarding your needs.

Email: [blmdxiao@gmail.com](mailto:blmdxiao@gmail.com)
WeChat: Alex_Bob_1988

**Comment by blmdxiao** [comment]
We will consider integrating [llama-parse](https://github.com/run-llama/llama_parse) for parsing PDF and other files.

**Comment by blmdxiao** [comment]
the file parsing capability of [llama-parse](https://github.com/run-llama/llama_parse)
https://github.com/gpt-open/rag-gpt/pull/70
