### ISSUE TITLE
Feature request: Support for custom OpenAI compatible endpoint and model name

### ISSUE THREAD

**Issue by FWangZil** [gpt-open/rag-gpt#71]
Support for custom OpenAI compatible endpoint and model name.
such as
https://kimi.moonshot.cn/

**Comment by blmdxiao** [comment]
Okay, I'll add it as soon as I can this week.

**Comment by blmdxiao** [comment]
Moonshot is already supported.
https://github.com/gpt-open/rag-gpt/pull/72
